one CLI command for dropping gisaid columns
nhhaidee/scovtree pull request #17
Opened 2021-06-15 20:13 UTC by nhhaidee

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
  - [ ] If you've added a new tool - add to the software_versions process and a regex to `scrape_software_versions.py`
  - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/scovtree/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nf-core/scovtree _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint .`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2021-06-15 21:37 UTC, nhhaidee commented
Just fixed bug #18 : Pango_lineage, Pangolin_version columns do not drop correctly

2021-06-16 19:47 UTC, peterk87 requested changes
Hi Hai,

This is an improvement over what you had previously.

I have a few major comments and concerns:

1. GISAID data cannot be made public without express permission by GISAID and the submitters of that data. Please remove any GISAID data you have uploaded to GitHub to ensure you're not in violation of their policies. Using NCBI sequence data should be alright and the metadata for those sequences can be spoofed for testing purposes.
2. Dropping metadata columns should be treated as more of a feature that may be nice to have in some scenarios. I want to re-emphasize that users can select metadata fields to highlight in the shiptv tree visualization so dropping columns as part of the workflow isn't something we need to focus much attention on. I don't think most users know ahead of time what columns they would want to drop before running the workflow especially if they are just providing the latest GISAID sequences and metadata as the `tar.xz` files they had originally downloaded. I think it's better to give users more data so they can pick and choose what they need for whatever they need it for.
3. There are assumptions that the format and content of GISAID metadata will not change in the future, but there's no guarantee that certain metadata fields may be dropped or added or the field names will change or that the order will change. It looks like it's assumed that there will be 22 columns in the GISAID metadata and they'll be in a particular order, but those assumptions may not hold. GISAID seems to change their output formats regularly without warning so it would be a good idea to have checks to see if the workflow can handle the metadata and ensure that as long as the essential fields are present, the workflow can still produce something useful.

Please also see my comments regarding certain lines of code.

Thanks,
Peter

2021-06-16 19:47 UTC, peterk87 commented on README.md
> +        There are  22 columns in GISAID metadata, please use columns as below:
There's no guarantee that there will always be 22 columns and that the columns will be named as such or in the order presented below.

2021-06-16 19:47 UTC, peterk87 commented on README.md
> +            --drop_gisaid_columns 'Is_reference?,Is_complete?,Is_high_coverage?,Is_low_coverage?,N-Content,GC-Content'
Typical command should be minimal. For this workflow, it should be

```bash
nextflow run nhhaidee/scovtree -profile <docker/singularity/conda> --input your_sarscov2_sequences.fasta
```
`reference_name` and `reference_fasta` should be set by default in `nextflow.config`. Users should not need to set these parameters for a typical analysis.

The `drop_gisaid_columns` option would not apply to this example since the user would not be specifying any GISAID data. It's also an optional option for advanced users.

2021-06-16 19:47 UTC, peterk87 commented on README.md
> +        Please note that DO NOT DROP 'Virus_name' columns otherwise columns will be empty in Shiptv Visualization and NO SPACE in parameters of --drop_gisaid_columns option
Why is this an issue? Aren't there checks in place to prevent this? The "Virus name" column should be treated as the index when reading the metadata table into a Pandas DataFrame (`pd.read_table(gisaid_metadata_handle, index_col=0)`)

2021-06-16 19:47 UTC, peterk87 commented on bin/filter_column_shiptv.py
> +        for col in drop_columns:
For loop to drop columns is not necessary. You can simply provide a list to `drop`

```python
df.drop(columns=list_of_columns_to_drop, inplace=True)
```

`inplace=True` if in-place mutation of DF is alright.

2021-06-16 19:47 UTC, peterk87 commented on bin/filter_column_shiptv.py
> +def main(metadata_input, metadata_output, metadata_aa_change, pangolin_report, drop_gisiad_columns):
This script's purpose seems to be primarily merging data for the same samples into a single table rather than filtering since it looks like the data is already filtered. Dropping metadata columns seems to be secondary and optional purpose. What about renaming the script to `merge_metadata.py`? The table output would be useful for users to open in Excel/LibreOffice as well as for shiptv tree visualization.

2021-06-16 19:47 UTC, peterk87 commented on bin/filter_column_shiptv.py
> +    df_shiptv_metadata = pd.read_table(metadata_input, sep='\t')
`pd.read_table` already sets `sep='\t'` by default.

2021-06-16 19:47 UTC, peterk87 commented on conf/test_gisaid_drop_columns.config
> +  gisaid_sequences     = 'https://raw.githubusercontent.com/nhhaidee/nf-test-datasets/main/sequences_gisaid.fasta'
GISAID data cannot be made public without express permission by GISAID and the submitters of that data. Please remove any GISAID data you have uploaded to GitHub to ensure you're not in violation of their policies. Using NCBI sequence data should be alright and the metadata for those sequences can be spoofed for testing purposes.

2021-06-16 19:47 UTC, peterk87 commented on modules/local/filter_column_shiptv.nf
> +    filter_column_shiptv.py -M $gisiad_metadata -m $filtered_shiptv_metadata -ma $aachange_metadata -p $pangolin_report \\
The primary purpose of this process and script doesn't seem to be filtering, but rather merging of GISAID metadata, Nextclade AA mutation data and Pangolin lineage data into a single data table. What about renaming the process to `MERGE_METADATA`?

2021-06-16 19:47 UTC, peterk87 commented on nextflow.config
> +  //drop_gisaid_columns = 'Virus_name,Type,Accession_ID,Collection_date,Location,Additional_location_information,Sequence_length,Host,Patient_age,Gender,Clade,Pango_lineage,Pangolin_version,Variant,A
Please remove unnecessary comments.

2021-06-16 20:02 UTC, nhhaidee commented on conf/test_gisaid_drop_columns.config
> +  gisaid_sequences     = 'https://raw.githubusercontent.com/nhhaidee/nf-test-datasets/main/sequences_gisaid.fasta'
OK. Deleted it

2021-06-16 20:02 UTC, nhhaidee commented on nextflow.config
> +  //drop_gisaid_columns = 'Virus_name,Type,Accession_ID,Collection_date,Location,Additional_location_information,Sequence_length,Host,Patient_age,Gender,Clade,Pango_lineage,Pangolin_version,Variant,A
Will update in next commit.

2021-06-17 16:55 UTC, nhhaidee commented on README.md
> +        Please note that DO NOT DROP 'Virus_name' columns otherwise columns will be empty in Shiptv Visualization and NO SPACE in parameters of --drop_gisaid_columns option
@peterk87 As I remember that the first column of metadata provided for shiptv must contain taxa name of tree, if we drop this column, there will be no metadata displayed in visualisation. Please correct me if I am wrong

I will remove this note  and code will prevent dropping this column

2021-06-17 16:55 UTC, nhhaidee commented on README.md
> +        There are  22 columns in GISAID metadata, please use columns as below:
@peterk87 I am also worrying about the changes in columns of metadata in the future. In the code, I just get columns of metadata, replacing space in column name by "_" and use these columns name through code of workflows, we don't need to worry about order of column.

Will add the process to check if the format of metadata changed or not. The below format will be used for checking against new metadata

[Virus_name, Type, Accession_ID, Collection_date, Location,
Additional_location_information, Sequence_length, Host,
Patient_age, Gender, Clade, Pango_lineage, Pangolin_version,
Variant, AA_Substitutions, Submission_date, Is_reference?,
Is_complete?, Is_high_coverage?, Is_low_coverage?, N-Content,
GC-Content]

2021-06-17 16:55 UTC, nhhaidee commented on README.md
> +            --drop_gisaid_columns 'Is_reference?,Is_complete?,Is_high_coverage?,Is_low_coverage?,N-Content,GC-Content'
Will update in next commit

2021-06-17 16:58 UTC, nhhaidee commented on conf/test_gisaid_drop_columns.config
> +  gisaid_sequences     = 'https://raw.githubusercontent.com/nhhaidee/nf-test-datasets/main/sequences_gisaid.fasta'
I downloaded sequences from NCBI and made spoof metadata. All sequences, metadata from GISAID were replaced

https://www.ncbi.nlm.nih.gov/labs/virus/vssi/#/virus?SeqType_s=Nucleotide&VirusLineage_ss=Severe%20acute%20respiratory%20syndrome%20coronavirus%202,%20taxid:2697049

2021-06-17 16:59 UTC, peterk87 commented on README.md
> +        Other options:
These details should be moved to `docs/usage.md`. The `README.md` document have enough info to allow someone to quickly get started with using this workflow with a typical use case.

2021-06-17 17:00 UTC, nhhaidee commented on bin/filter_column_shiptv.py
> +def main(metadata_input, metadata_output, metadata_aa_change, pangolin_report, drop_gisiad_columns):
@peterk87 Updated by commit https://github.com/nhhaidee/scovtree/pull/17/commits/d9295d05a0f64d08af35d292dac7e50e2ad4ef92

2021-06-17 17:01 UTC, nhhaidee commented on modules/local/filter_column_shiptv.nf
> +    filter_column_shiptv.py -M $gisiad_metadata -m $filtered_shiptv_metadata -ma $aachange_metadata -p $pangolin_report \\
Updated by https://github.com/nhhaidee/scovtree/pull/17/commits/d9295d05a0f64d08af35d292dac7e50e2ad4ef92

2021-06-17 17:01 UTC, nhhaidee commented on nextflow.config
> +  //drop_gisaid_columns = 'Virus_name,Type,Accession_ID,Collection_date,Location,Additional_location_information,Sequence_length,Host,Patient_age,Gender,Clade,Pango_lineage,Pangolin_version,Variant,A
Updated by https://github.com/nhhaidee/scovtree/pull/17/commits/d9295d05a0f64d08af35d292dac7e50e2ad4ef92

2021-06-17 17:04 UTC, peterk87 commented on nextflow.config
> +  //drop_gisaid_columns = 'Virus_name,Type,Accession_ID,Collection_date,Location,Additional_location_information,Sequence_length,Host,Patient_age,Gender,Clade,Pango_lineage,Pangolin_version,Variant,A
Please reference commit that the changes were made in, e.g.

"Removed in d9295d0"

Also if possible, try to make one change per commit so it's easier to see and track the changes made.

2021-06-17 17:05 UTC, nhhaidee commented on README.md
> +        Other options:
OK

2021-06-17 17:08 UTC, peterk87 commented on README.md
> +        Please note that DO NOT DROP 'Virus_name' columns otherwise columns will be empty in Shiptv Visualization and NO SPACE in parameters of --drop_gisaid_columns option
@nhhaidee yes, shiptv expects the first column (the index column) to contain taxa names that match the tree. What I meant was that it shouldn't even be possible to drop that column, that is, if a user specifies that the column be dropped (for whatever reason) then it should be simply be *ignored*! So this issue should not exist since the code should be preventing it from happening since it is an essential column in the metadata table.

2021-06-17 17:10 UTC, peterk87 commented on README.md
> +            --drop_gisaid_columns 'Is_reference?,Is_complete?,Is_high_coverage?,Is_low_coverage?,N-Content,GC-Content'
Please only reference the commit where the change was made unless you think no change is required or if you require further clarification on what I meant in my comment.

2021-06-17 17:12 UTC, nhhaidee commented on README.md
> +        Please note that DO NOT DROP 'Virus_name' columns otherwise columns will be empty in Shiptv Visualization and NO SPACE in parameters of --drop_gisaid_columns option
@peterk87 The code prevented it from happening even user specify drop this column

2021-06-17 17:14 UTC, nhhaidee commented on bin/filter_column_shiptv.py
> +        for col in drop_columns:
@peterk87 : I use for loop because want to check if Virus_name in drop columns list, code can prevent this column from dropping

2021-06-17 17:18 UTC, nhhaidee commented on nextflow.config
> +  //drop_gisaid_columns = 'Virus_name,Type,Accession_ID,Collection_date,Location,Additional_location_information,Sequence_length,Host,Patient_age,Gender,Clade,Pango_lineage,Pangolin_version,Variant,A
@peterk87 OK, I will made only change in the next commit

2021-06-17 17:36 UTC, peterk87 commented on bin/filter_column_shiptv.py
> +        for col in drop_columns:
Why not filter `drop_columns` for columns that actually exist in the metadata table and can be dropped?

Also, why is `aa_substitution_change` something that needs to be specified as a column to drop to not merge in the Nextclade AA mutation data? That is very confusing. It should be merged by default if the AA mutation matrix is specified, otherwise, it's not added to the metadata table since it doesn't exist.

```python
if metadata_aa_change:
    # assuming index for df_metadata is sample names
    df_metadata = pd.concat([df_metadata, pd.read_table(metadata_aa_change, index_col=0])
```

2021-06-17 19:53 UTC, peterk87 commented on README.md
> +        Other options:
FYI basic script for generating markdown from `nextflow_schema.json`:

https://github.com/peterk87/nf-iav-illumina/blob/master/docs/nextflow_schema_json_to_markdown.py

2021-06-18 15:07 UTC, nhhaidee commented on README.md
> +        There are  22 columns in GISAID metadata, please use columns as below:
This concern will be addressed by https://github.com/nhhaidee/scovtree/issues/24

2021-06-18 16:20 UTC, nhhaidee commented on bin/filter_column_shiptv.py
> +        for col in drop_columns:
What do you think as below?

1. It is confusing when specifying columns to drop, instead user specify columns that they want to visualise by a parameter `--visualise-gisaid-metadata 'Virus_name,Type,Accession_ID,Collection_date,Location'` (default: visualises all columns)
2. A option `--visualise-aa-change true/false` (default: true)

2021-06-18 19:10 UTC, peterk87 commented on bin/filter_column_shiptv.py
> +        for col in drop_columns:
1. That's a great idea. It'd be more intuitive to select what you want rather than what you don't want. It'd also be nice if users could specify non-exact strings for partial case-insensitive matching of fields to be selected, e.g. `"name,date,acc,type,lin,loc"`. `visualise` -> `select` since the specified be selected.
2. Just check if an AA matrix file is specified; no need for redundant CLI options. That option should be for the workflow rather than this script. If the Nextclade derived AA mutation matrix is generated, then it should be added to the metadata table.

2021-06-18 21:29 UTC, merged