handle low abundance lineages better
nhhaidee/scovtree pull request #35
Opened 2021-07-01 00:35 UTC by nhhaidee

This PR address enhancement https://github.com/nhhaidee/scovtree/issues/34

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
  - [ ] If you've added a new tool - add to the software_versions process and a regex to `scrape_software_versions.py`
  - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nhhaidee/scovtree/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nhhaidee/scovtree _branch_ on the [nhhaidee/nf-test-datasets](https://github.com/nhhaidee/nf-test-datasets) repository.
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2021-07-01 13:37 UTC, nhhaidee commented on bin/filter_msa.py
> +        # There is no low abundance lineages, proportion of all lineages are greater than low_abundance_value
Set `low_abundance_value` to find low abundance linages

2021-07-01 13:37 UTC, nhhaidee commented on bin/filter_msa.py
> +        else:
If there is now low abundance linages then sampling as we did

2021-07-01 13:37 UTC, nhhaidee commented on bin/filter_msa.py
>      logging.info(f'Writing {len(keep_samples)} of {len(seq_samples)} sequences to "{output_fasta}".')
If found low abundance lineages then add them to `keep_samples` and sampling high abundance lineages only

2021-07-01 13:40 UTC, nhhaidee commented
@peterk87 I add code to handle low abundance lineage better, please let me know your comment on this. I did as your comments with a little bit change.

2021-07-02 13:42 UTC, nhhaidee commented on bin/filter_msa.py
> +            keep_samples |= set(df_less_n_gaps['sample'].sample(n=n_to_sample))
If there is no low abundance linages then sampling as we did

2021-07-02 13:42 UTC, nhhaidee commented on bin/filter_msa.py
> +            keep_samples |= set(df_less_n_gaps['sample'].sample(n=n_to_sample))
If found low abundance lineages then add them to keep_samples and sampling high abundance lineages only

2021-07-02 15:01 UTC, peterk87 commented
@nhhaidee All lineages at the MSA stage should be represented in equal proportions if possible. This code doesn't seem to do that. 

What should be happening is that if lineage `A` only has 100 seqs in the MSA and lineage `B` with 1000 and `C` with 98900, then all `A` sequences should make it to the tree stage, while equal proportions of `B` and `C` make up the difference up to, let's say 1000 max taxa in the tree. 

Additionally, these changes do not address the initial filtering of the GISAID data performed in 

https://github.com/nhhaidee/scovtree/blob/7c331a11663acbada7cfdc99938c7915bad1ecf6/bin/filter_gisaid.py#L65-L72

At this stage, the larger lineages could dominate the sampled data potentially resulting in no GISAID seq data being filtered for smaller lineages if larger lineages are also present in the user input data.

2021-07-02 15:27 UTC, nhhaidee commented
@peterk87 Below is an example that I did test. 
```python
df['Pango_lineage'].value_counts(ascending=True)
B.1.618        115
B.1.617.2    45038
B.1.2        52220
df['Pango_lineage'].value_counts(normalize=True, ascending=True).to_frame('proportion')
           proportion
B.1.618      0.001181 #low abundance
B.1.617.2    0.462531
B.1.2        0.536288
```
I used `normalize=True` to find the proportion of lineages in MSA filtering stage, based on `low_abundance_value` (user can set this value), we can know which linage is low abundance. The code did two things:

https://github.com/nhhaidee/scovtree/blob/4726e8671b1e7bdcab68827361a41d5c5a905911/bin/filter_msa.py#L52-L53 
1. If no low abundance linage found then do sampling as we did 
 https://github.com/nhhaidee/scovtree/blob/4726e8671b1e7bdcab68827361a41d5c5a905911/bin/filter_msa.py#L54-L59 
2. If found low abundance lineages then add all to `keep_samples` and sampling high abundance lineages only
 https://github.com/nhhaidee/scovtree/blob/4726e8671b1e7bdcab68827361a41d5c5a905911/bin/filter_msa.py#L60-L69

2021-07-02 16:25 UTC, nhhaidee commented
The above strategy can be applied for `bin/filter_gisiad.py`?

2021-07-02 17:16 UTC, peterk87 commented
@nhhaidee it would be better to not have a low abundance threshold value at all and to instead try to represent each lineage as equally as possible irrespective of the counts - normalized or not. 

The sampling should be done separately for each unique lineage to ensure that each lineage is properly represented in the MSA for phylogenetic analysis. For example:

Python like pseudo-code:
```python
# max number of seqs to keep
max_msa_seqs = 1000
# sorted in ascending order
lineage_counts = [
    (A, 100),
    (B, 1000),
    (C, 98900)
]
keep_samples = set(<initialized with user seq ids>)

n_lineages = len(lineage_counts)
# initial value of seqs to try for for each lineage
seqs_per_lineage = int((max_msa_seqs - len(keep_samples)) / n_lineages)

for i, (lineage, count) in enumerate(lineage_counts):
    seqs_in_lineage = df[df.lineage == lineage].index
    if count < seqs_per_lineage:
        keep_samples |= set(seqs_in_lineage)
    else:
        keep_samples |= set(seqs_in_lineage.sample(n=seqs_per_lineage))
    if n_lineages < i + 1:
        # recalculate seqs_per_lineage
        seqs_per_lineage = (max_msa_seqs - len(keep_samples)) / (n_lineages - i + 1)
```

Variables from iteration through for loop
```
seqs_per_lineage : 333

i                : 0
count            : 100
lineage          : 'A'
len(keep_samples): 100
seqs_per_lineage : 450

i                : 1
count            : 1000
lineage          : 'B'
seqs_per_lineage : 450

i                : 2
count            : 98900
lineage          : 'B'
seqs_per_lineage : 450
```

This kind of sampling should be done at all applicable stages:

- initial GISAID filtering (`bin/filter_gisaid.py`)
- MSA filtering (`bin/filter_msa.py`)
- tree taxa selection (`bin/prune_tree.py`)

to ensure that each lineage is represented as equally as possible.

2021-07-03 23:19 UTC, nhhaidee commented
@peterk87 I made the changes on `bin/filter_gisaid.py` and `bin/filter_msa.py` based on your suggestion. The test seems to be very good, the trees are well balanced.

Below are the regression test cases that I ran with these changes and please find attached for shiptv virtualization
[test.zip](https://github.com/nhhaidee/scovtree/files/6759166/test.zip)


Test cases:
Sample Lineages in GISAID B.1.2 (> 100,000 sequences); B.1.617.2 ( > 37,000 sequences); B.1.618 ( > 180 sequences)
Input sequences: B.1.2 has 2 sequences, B.1.617.2 has 1 sequence, B.1.618 has 1 sequence

Test Case 1: 2 input consensus sequences belong to B.1.2 lineage (Passed)
Test Case 2: 1 input consensus sequence belong to B.1.617.2 lineage (No Run)
Test Case 3: 1 input consensus sequence belong to B.1.618 lineage (Passed)
Test Case 4: Mix consensus sequences (B.1.2 + B.1.617.2) (No Run)
Test Case 5: Mix consensus sequences (B.1.2 + B.1.618) (No Run)
Test Case 6: Mix consensus sequences (B.1.617.2 + B.1.618) (Failed)
Test Case 7: Mix consensus sequences (B.1.2 + B.1.617.2 + B.1.618) (Passed)
Test Case 8: test_gisaid, test_gisaid_custom (Passed)

2021-07-05 17:36 UTC, peterk87 requested changes
The trees you generated look great with the updated sampling code. They are definitely more balanced.

I just have a few minor comments.

Thanks @nhhaidee!

2021-07-05 17:36 UTC, peterk87 commented on bin/filter_gisaid.py
> +    logging.info(f'{df_subset.columns}')
This logging message could be more informative. It seems more like a debugging message. It could log the subset dataframe `.shape`?

2021-07-05 17:36 UTC, peterk87 commented on bin/filter_gisaid.py
> +            logging.info(f'No need to sampling {lineage}')
Might be a good idea to make this a bit more informative in case there are issues later on:
```python
logging.info(f'No need to sample lineage "{lineage}" sequences (count={row["count"]}; less than {seqs_per_lineage} seqs per lineage)')
```

2021-07-05 17:36 UTC, peterk87 commented on bin/filter_msa.py
> +        sample_lineage = set(df[df.index == list(samples)[0]]['Pango_lineage'])
Code could be simplified a bit to extract common variable and just access the scalar value for the `lineage` with `df.loc[index_val, column_name]`:

```python

sample: str = list(samples)[0]
lineage: str = df.loc[sample, 'Pango_lineage']
seq_recs.append(dict(
    sample=sample,
    lineage=lineage,
    seq_n=seq.count('N'),
    seq_gap=seq.count('-'),
))
```

2021-07-06 14:46 UTC, nhhaidee commented on bin/filter_gisaid.py
> +    logging.info(f'{df_subset.columns}')
Fixed by https://github.com/nhhaidee/scovtree/pull/35/commits/dd9be089584144b053df95906533b020344bb8ea

2021-07-06 14:46 UTC, nhhaidee commented on bin/filter_gisaid.py
> +            logging.info(f'No need to sampling {lineage}')
Fixed by https://github.com/nhhaidee/scovtree/pull/35/commits/dd9be089584144b053df95906533b020344bb8ea

2021-07-06 17:09 UTC, nhhaidee commented on bin/filter_msa.py
> +        sample_lineage = set(df[df.index == list(samples)[0]]['Pango_lineage'])
Updated by https://github.com/nhhaidee/scovtree/pull/35/commits/8756cd61db3d3cb3dcebb27f1b8ddb50afef7fa3

I changed code like this `lineage = set(df.loc[sample, 'Pango_lineage') `, but not sure why it returned strange result with some duplicated strains, but there is no problem with below code

https://github.com/nhhaidee/scovtree/blob/8756cd61db3d3cb3dcebb27f1b8ddb50afef7fa3/bin/filter_msa.py#L101-L110

2021-07-06 21:08 UTC, peterk87 commented on bin/filter_msa.py
> +        sample_lineage = set(df[df.index == list(samples)[0]]['Pango_lineage'])
Okay, it sounds like duplicate data should be properly dealt with prior to this step, as in, there should be no duplicate "virus names" at this point in the analysis. I created an issue (#36) that can be dealt with in a separate PR.

2021-07-06 21:08 UTC, peterk87 approved these changes

2021-07-06 21:12 UTC, nhhaidee commented
Thanks @peterk87 . I will merge this PR and release this enhancement.

2021-07-06 21:12 UTC, peterk87 commented
@nhhaidee Since this is a merge into master branch, the version needs to be bumped (e.g. to `1.1.0`). 

https://github.com/nhhaidee/scovtree/blob/8756cd61db3d3cb3dcebb27f1b8ddb50afef7fa3/nextflow.config#L175

2021-07-06 21:29 UTC, merged